<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class PersistProductPrice extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'current_price.value'           => 'sometimes|numeric',
            'current_price.currency_code'   => 'required_with:current_price.value'
        ];
    }

    public function messages()
    {
        return parent::messages(); // TODO: Change the autogenerated stub
    }

    protected function getValidatorInstance()
    {
        return validator($this->json()->all(), $this->rules(), $this->messages());
    }
}
